# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d97a00b27e51d4a4e27a325403bad6aa5d4638348ad21665d0063374b36cd22dce094e48c1f67c46d249b49589679173be647168e9ead6508ef3d04ef32555

test:
  secret_key_base: 2e48c9daa8dcf7cbeb9b69a5f7f6197703f46497f72732b8ba1aca88a0cf65a56d6395049e14352863c3ee8c45de5a94450eff92396e529925f14032f6b1af33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
